sudo: required

services:
  - docker

script:
  - docker build -t docker-robot-framework .

after_success:
  - docker run -v test:/opt/robotframework/tests:Z -e BROWSER=chrome docker-robot-framework
  - docker run -v test:/opt/robotframework/tests:Z -e BROWSER=firefox docker-robot-framework

