---
resources:
- name: docker-robot-framework
  type: git
  icon: github-circle
  source:
    uri: http://github.com/95rade/docker-robot-framework.git
    branch: master
    paths: [Dockerfile]      # find Dockerfile in repo root.

- name: new-robot-image
  type: docker-image
  source:
    username: ((dockerhub-username))
    password: ((dockerhub-password))
    repository: rade95/new-robot-image

- name: slack-alert
  type: slack-notification
  icon: slack
  source:
    url: ((slack-webhook))

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.3.0

jobs:
- name: build-robot-docker-image
  public: true
  serial: true
  plan:
  - get: docker-robot-framework
    trigger: true
  #- get: 30m-timer
  - put: new-robot-image
    params: {build: docker-robot-framework}

  on_failure:
    put: slack-alert
    params:
      channel: '#concourse'
      #username: 'rade'
      #icon_emoji: ':concourse:'
      #icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      #icon_url: https://binged.it/2Pl9tD5
      icon_url: https://binged.it/35lbg0u
      silent: true
      text: |
            *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) FAILED to build image
            https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  on_success:
    put: slack-alert
    params:
      channel: '#concourse'
      #username: 'rade'
      #icon_emoji: ':concourse:'
      #icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      #icon_url: https://binged.it/2Pl9tD5
      icon_url: https://binged.it/35lbg0u
      silent: true
      text: |
            *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) SUCCESS - Image has been published
            https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
