---
jobs:
- name: build-robot-docker-image
  public: true
  serial: true
  plan:
  - get: docker-robot-framework
    trigger: true
  #- get: 30m-timer
  - put: new-robot-image
    params: {build: docker-robot-framework}

resources:
- name: docker-robot-framework
  type: git
  source:
    uri: http://github.com/95rade/docker-robot-framework.git
    branch: master
    paths: [Dockerfile]      # find Dockerfile in repo root.

- name: new-robot-image
  type: docker-image
  source:
    username: ((dockerhub-username))
    password: ((dockerhub-password))
    repository: rade95/new-robot-image
    #repository: rade95/new-robot-image     # my robot image in dockerhub
