---
resources:
  - name: docker-robot-framework
    type: git
    icon: github-circle
    source: &repo-source
      uri: https://github.com/95rade/docker-robot-framework
      branch: master
      paths: [Dockerfile]
  - name: jdriven-robot-image
    type: docker-image
    source:
      username: ((dockerhub-username))
      password: ((dockerhub-password))
      #repository: rade95/new-robot-image
      repository: rade95/jdriven-robot-image
      tag: latest

  - name: timer-6h
    type: time
    icon: clock-outline
    source:
      interval: 6h

  - name: slack-alert
    type: slack-notification
    source:
      url: ((slack-webhook))

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: v1.3.0

jobs:

  - name: build-robot-docker-image
    public: true
    serial: true
    plan:
    - get: docker-robot-framework
      trigger: true
    - get: timer-6h
    - put: jdriven-robot-image
      params: {build: docker-robot-framework}
      on_failure:
        put: slack-alert
        params:
          channel: '#concourse'
          #username: 'rade'
          #icon_emoji: ':concourse:'
          #icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
          #icon_url: https://binged.it/2Pl9tD5
          icon_url: https://binged.it/35lbg0u
          silent: true
          text: |
              *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) FAILED to build image
              https://192.168.1.18:8080/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      on_success:
        put: slack-alert
        params:
          channel: '#concourse'
          #username: 'rade'
          #icon_emoji: ':concourse:'
          #icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
          #icon_url: https://binged.it/2Pl9tD5
          icon_url: https://binged.it/35lbg0u
          silent: true
          text: |
              *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) SUCCESS - Image has been published
              https://192.168.1.18:8080/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: run-tests
    plan:
      - get: jdriven-robot-image
        trigger: true
        passed: [build-robot-docker-image]
      - get: docker-robot-framework
        trigger: true
        passed: [build-robot-docker-image]
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: rade95/jdriven-robot-image
              username: ((dockerhub-username))
              password: ((dockerhub-password))
          inputs:
            #- name: new-robot-image
            - name: docker-robot-framework
          run:
            path: /bin/sh
            args:
            - -c
            - |
              cd docker-robot-framework/scripts
              ./run_suite.sh

        on_failure:
          put: slack-alert
          params:
            channel: '#concourse'
            #username: 'rade'
            #icon_emoji: ':concourse:'
            #icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
            #icon_url: https://binged.it/2Pl9tD5
            icon_url: https://binged.it/35lbg0u
            silent: true
            text: |
                  *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) FAILED to build image
                  https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        on_success:
          put: slack-alert
          params:
            channel: '#concourse'
            #username: 'rade'
            #icon_emoji: ':concourse:'
            #icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
            #icon_url: https://binged.it/2Pl9tD5
            icon_url: https://binged.it/35lbg0u
            silent: true
            text: |
                  *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) SUCCESS - Image has been published
                  https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
