---
jobs:
#- name: build-robot-docker-image
#  public: true
#  serial: true
#  plan:
#  - get: docker-robot-framework
#    trigger: true
#  - get: 30m-timer
#  - put: robot-image
#    params: {build: docker-robot-framework}

- name: run-robot-tests
  plan:
  - get: robot-image
    #passed: [build-robot-docker-image]
    #trigger: true
  - get: docker-robot-framework
    #passed: [build-robot-docker-image]
    trigger: true
  - get: 60m-timer
  - task: run-tests
    image: robot-image
    params: 
        OWNER: rade
    config:
      platform: linux
      inputs:
      - name: docker-robot-framework  # input dir for script is our repo folder

      run:
        path: /bin/sh
        args:
        - -exc
        #- -c
        - |
          whoami
          #env
          pwd
          ls -al
          cd docker-robot-framework
          ls -al
          chmod +x run_tests.sh
          ls -al
          ./run_tests.sh

      #run:
      #  path: docker-robot-framework/test/run_tests.sh
      #  args: []


resources:

- name: 60m-timer
  type: time
  source:
    interval: 60m

- name: docker-robot-framework
  type: git
  source:
    uri: https://github.com/95rade/docker-robot-framework.git
    branch: master
    paths: [Dockerfile]      # find Dockerfile in repo root.

- name: robot-image
  type: docker-image
  source:
    username: ((dockerhub-username))
    password: ((dockerhub-password))
    #repository: ((dockerhub-username))/robot-docker-image
    repository: rade95/robot-image