---
jobs:
- name: build-robot-docker-image
  public: true
  serial: true
  plan:
  - get: docker-robot-framework
    trigger: true
  #- get: 30m-timer
  - put: robot-image
    params: {build: docker-robot-framework}

- name: run-robot-tests
  public: true
  plan:
  - get: docker-robot-framework
    passed: [build-robot-docker-image]
    trigger: true
  - task: run-robot-tests
    file: docker-robot-framework/run_tests.yml
      #run:
      #  path: /bin/sh
      #  args:
      #  - -exc
        #- -c
      #  - |
      #      whoami
      #      #env
      #      pwd
      #      ls -al
      #      cd docker-robot-framework
      #      ls -al
      #      chmod +x run_tests.sh
      #      ls -al
      #      ./run_tests.sh

      #run:
      #  path: docker-robot-framework/run_tests.sh
      #  args: []


resources:
#- name: 30m-timer
#  type: time
#  source:
#    interval: 30m

- name: docker-robot-framework
  type: git
  source:
    uri: http://github.com/95rade/docker-robot-framework.git
    branch: master
    paths: [Dockerfile]      # find Dockerfile in repo root.

- name: robot-image
  type: docker-image
  source:
    username: ((dockerhub-username))
    password: ((dockerhub-password))
    #repository: ((dockerhub-username))/robot-docker-image
    repository: rade95/robot-image
