---
resources:
  - name: docker-robot-framework
    type: git
    source: &repo-source
      uri: https://github.com/95rade/docker-robot-framework
      #uri: https://github.com/do-community/hello_hapi
      branch: master

jobs:
  - name: run-tests!
    plan:
      - get: docker-robot-framework
        trigger: true
        #passed: [Install dependencies]
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: rade95/robot-image
              username: ((dockerhub-username))
              password: ((dockerhub-password))
          inputs:
            - name: docker-robot-framework
          run:
            path: /bin/sh
            args:
            - -c
            - |
              #pwd
              #ls -ltr
              cd docker-robot-framework
              #ls -ltr
              ./test.sh
