---
resources:
  - name: docker-robot-framework
    type: git
    source: &repo-source
      uri: https://github.com/95rade/docker-robot-framework
      branch: master
      paths: [Dockerfile]
  - name: new-robot-image
    type: docker-image
    source:
      username: ((dockerhub-username))
      password: ((dockerhub-password))
      repository: rade95/new-robot-image
      tag: latest

  - name: slack-alert
    type: slack-notification
    source:
      url: ((slack-webhook))

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: v1.3.0

jobs:
  - name: build-robot-docker-image
    public: true
    serial: true
    plan:
    - get: docker-robot-framework
      trigger: true
    #- get: 30m-timer
    - put: new-robot-image
      params: {build: docker-robot-framework}
      on_failure:
        put: slack-alert
        params:
          channel: '#concourse'
          #username: 'homer'
          icon_emoji: ':airplane:'
          silent: true
          text: |
              *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) FAILED to build image
              https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      on_success:
        put: slack-alert
        params:
          channel: '#concourse'
          #username: 'homer'
          icon_emoji: ':airplane:'
          silent: true
          text: |
              *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) SUCCESS - Image has been published
              https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: run-tests!
    plan:
      - get: new-robot-image
        trigger: true
        passed: [build-robot-docker-image]
      - get: docker-robot-framework
        trigger: true
        passed: [build-robot-docker-image]
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: rade95/new-robot-image
              username: ((dockerhub-username))
              password: ((dockerhub-password))
          inputs:
            - name: new-robot-image
            - name: docker-robot-framework
          run:
            path: /bin/sh
            args:
            - -c
            - |
              cd docker-robot-framework
              ./test.sh

        on_failure:
          put: slack-alert
          params:
            channel: '#concourse'
            #username: 'homer'
            icon_emoji: ':airplane:'
            silent: true
            text: |
                  *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) FAILED to build image
                  https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        on_success:
          put: slack-alert
          params:
            channel: '#concourse'
            #username: 'homer'
            icon_emoji: ':airplane:'
            silent: true
            text: |
                  *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) SUCCESS - Image has been published
                  https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
