resource_types:
  - name: robot-image-cache (npm-cache)
    type: docker-image
    source:
      #repository: ymedlop/npm-cache-resource
      repository: rade95/robot-image
      tag: latest

resources:
  - name: docker-robot-framework (hello_hapi)
    type: git
    source: &repo-source
      uri: https://github.com/95rade/docker-robot-framework
      #uri: https://github.com/do-community/hello_hapi
      branch: master
  - name: robot-image (dependency-cache)
    type: robot-image-cache (npm-cache)
    source:
      <<: *repo-source
      paths:
        - package.json

jobs:
  - name: Install dependencies
    plan:
      - get: docker-robot-framework (hello_hapi)
        trigger: true
      - get: robot-image (dependency-cache)
  - name: Run Robot tests
    plan:
      - get: docker-robot-framework (hello_hapi)
        trigger: true
        passed: [Install dependencies]
      - get: robot-image (dependency-cache)
        passed: [Install dependencies]
      - task: run the test suite
        file: docker-robot-framework/ci/tasks/run_tests.yml
