resources:
- name: docker-robot-framework
  trigger: true
  type: git
  source:
    uri: https://github.com/95rade/docker-robot-framework.git
    branch: master
- name: robot-image
  type: docker-image
  source:
    repository: rade95/robot-image

jobs:
- name: run-robot-tests-in-docker-image
  public: true
  plan:
  - get: docker-robot-framework
  - get: robot-image
  - task: run-robot-tests-in-docker
    file: docker-robot-framework/ci/tasks/run_tests.yml
