resources:
- name: docker-robot-framework
  type: git
  source:
    uri: https://github.com/95rade/docker-robot-framework.git
    branch: master

jobs:
- name: run-robot-tests
  public: true
  plan:
  - get: docker-robot-framework
  - task: hello-robot
    file: docker-robot-framework/ci/tasks/run_tests.yml
